### PR TITLE
First task

### PR DESCRIPTION
**Pull request by JulianK1608**
frac/3 with 3rd argument being the digits the nominator and denominator should be rounded to, before dividing.
But apperently there's some kind of problem with "Install Packages", but i don't know how to solve that :/

### CODE REVIEW

**Comment by JulianK1608** [comment]
*"Install pack"

**Comment by mgondan** [comment]
Please elaborate: But apperently there's some kind of problem with "Install Packages", but i don't know how to solve that :/

**Comment by JulianK1608** [comment]
Well the test doesn't run through, but i kind of understood now. The tests for tstat etc. don't run through anymore

**Comment by JulianK1608** [comment]
Ah wait i got it

**Comment by mgondan** [comment]
Thanks, merged, please proceed with the next task

**Pull request merged**
