### PR TITLE
Added t-distribution

### PR DESCRIPTION
**Pull request by jeremyirilli**

### CODE REVIEW

**Comment by mgondan** [comment]
Could you explain this a bit?

=> eval(A, X),
    L = X,
    U = X,
    Res = L...U.

**Comment by mgondan** [comment]
Can we deal with fractional df?

interval:int_hook(pt, pt(..., ... [was: atomic], atomic)).

The code below does it anyway, see the +, + in the mono declaration .

**Comment by mgondan** [comment]
For the tests, add helper predicate (?)

L > 0.3279, U < 0.3797 should be equality/similarity, e.g. interval(round(L...U, 4), 0.3279 ... 0.3797)

**Comment by jeremyirilli** [comment]
Regarding the degree freedoms, your guess was right, increasing for x < 0, for x > 0, it's decreasing, for upper tail, the reverse for lower tail.

> pt(2, 1:5, lower.tail = TRUE)
[1] 0.8524164 0.9082483 0.9303370 0.9419417 0.9490303
> pt(-2, 1:5, lower.tail = TRUE)
[1] 0.14758362 0.09175171 0.06966298 0.05805826 0.05096974

> pt(2, 1:5, lower.tail = FALSE)
[1] 0.14758362 0.09175171 0.06966298 0.05805826 0.05096974
> pt(-2, 1:5, lower.tail = FALSE)
[1] 0.8524164 0.9082483 0.9303370 0.9419417 0.9490303

I updated the predicates and added the helper predicate in the tests.

Are you also suggesting to change the declaration of each predicate of the t-distribution to allow intervals for the degree of freedoms?

**Comment by mgondan** [comment]
Yes, and please check the case that x in pt(x, df) includes 0. That should still be feasible.*
*Do we have pnorm/3? Then you can check the behavior for sigma^2 for inspiration, it has a similar effect.

qt should work, as well. More problems may arise in dt :-/

**Comment by jeremyirilli** [comment]
I removed the "atomic" from the definitions.

**Comment by mgondan** [comment]
Don't we have a helper predicate that doesn't need "atomic"?

So that we can use interval(pt(-0.5... -0.2, 5, true), Res) instead of interval(pt(-0.5... -0.2, atomic(5), atomic(true)), Res)

Just asking

**Comment by jeremyirilli** [comment]
For the df it works without "atomic", for "true" and "false" not yet.

image

**Comment by mgondan** [comment]
Can you try to fix this?

**Comment by jeremyirilli** [comment]
> Can you try to fix this?

It seems to work except for round/2

<br>

image

**Pull request merged**
